//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAP.InsuranceSample.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientContractCover
    {
        public int ClientContractCoverId { get; set; }
        public int ClientContractId { get; set; }
        public int CoverId { get; set; }
        public double Percentage { get; set; }
    }
}
