//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAP.InsuranceSample.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientContract
    {
        public int ClientContractId { get; set; }
        public int ClientId { get; set; }
        public int PolicyId { get; set; }
        public System.DateTime EffectDate { get; set; }
        public short CoverageMonths { get; set; }
        public decimal MonthlyPremium { get; set; }
        public int RiskTypeId { get; set; }
        public bool Cancelled { get; set; }
    }
}
