//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAP.InsuranceSample.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Policy
    {
        public int PolicyId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public decimal MonthlyPremium { get; set; }
        public int RiskTypeId { get; set; }
        public bool Deleted { get; set; }
    }
}
